services:
  python-server:
    container_name: supplychain-python-server  # Custom container name
    build: ./backend/python-api
    ports:
      - "5001:5001"
    volumes:
      - ./backend/python-api:/app
    environment:
      - PYTHONUNBUFFERED=1

  nextjs-app:
    container_name: supplychain-nextjs-app  # Custom container name
    build: ./Supply-chain-main
    ports:
      - "3000:3000"
    volumes:
      - ./Supply-chain-main:/app
    depends_on:
      - python-server
