name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 52.87.170.241
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: OPENAI_API_KEY
          script: |
            # ----- Initial Setup -----
            cd ~
            sudo yum update -y
            sudo yum install -y git docker

            # ----- Install Node.js for Next.js -----
            curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2

            # ----- Install Python for Flask -----
            sudo yum install -y python3-pip python3-devel gcc
            python3 -m pip install --user virtualenv

            # ----- Docker Setup (Optional for future use) -----
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user || true

            # ----- Clone/Update Repo -----
            if [ ! -d "supplychain-app" ]; then
              git clone https://github.com/IT21373848/smart-garment-chain.git supplychain-app
            fi

            cd supplychain-app
            git reset --hard
            git pull origin main

            # ===== Flask (Gunicorn + systemd) =====
            cd apps/backend/python-api

            # Create virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Install dependencies with custom TMPDIR
            mkdir -p ~/tmp_pip
            TMPDIR=~/tmp_pip pip install -r src/requirements.txt gunicorn

            # Create systemd service file
            sudo bash -c 'cat > /etc/systemd/system/flask-api.service <<EOL
            [Unit]
            Description=Flask API with Gunicorn
            After=network.target

            [Service]
            User=ec2-user
            WorkingDirectory=/home/ec2-user/supplychain-app/apps/backend/python-api
            Environment="OPENAI_API_KEY=$OPENAI_API_KEY"
            ExecStart=/home/ec2-user/supplychain-app/apps/backend/python-api/venv/bin/gunicorn \
              --workers 4 \
              --bind 0.0.0.0:5001 \
              src.app:app
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOL'

            # Reload and start Flask service
            sudo systemctl daemon-reload
            sudo systemctl enable flask-api
            sudo systemctl restart flask-api

            # ===== Next.js (PM2) =====
            cd ../../Supply-chain-main

            # Install dependencies
            npm install --frozen-lockfile

            # Build and start with PM2
            npm run build
            pm2 delete nextjs || true
            pm2 start npm --name nextjs -- start

            # Persist PM2 process list
            pm2 save
            sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ec2-user --hp /home/ec2-user

            # ----- Verify Services -----
            echo "Flask status:"
            sudo systemctl status flask-api --no-pager

            echo "PM2 list:"
            pm2 list