name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 52.87.170.241
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GEMINI_API_KEY
          script: |
            # ----- Initial Setup -----
            cd ~
            sudo yum update -y
            sudo yum install -y git docker python3-pip python3-devel gcc

            # ----- Install Node.js for Next.js -----
            curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2

            # ----- Docker Setup -----
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user || true

            # ----- Clone/Update Repo -----
            if [ ! -d "supplychain-app" ]; then
              git clone https://github.com/IT21373848/smart-garment-chain.git supplychain-app
            fi

            cd supplychain-app
            git reset --hard
            git pull origin main

            # ===== Flask Setup =====
            cd apps/backend/python-api

            # Create/update virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Install Python dependencies
            pip install -r src/requirements.txt
            deactivate

            # Start Flask with PM2 (development server)
            pm2 delete flask-dev || true
            pm2 start venv/bin/python --name flask-dev -- src/app.py
            pm2 save

            # ===== Next.js Setup =====
            cd ../../Supply-chain-main

            # Install dependencies and build
            npm install --frozen-lockfile
            npm run build

            # Start with PM2
            pm2 delete nextjs || true
            pm2 start npm --name nextjs -- start
            pm2 save
            sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ec2-user --hp /home/ec2-user

            # ===== Verification ======
            echo "Flask service status:"
            sudo systemctl status flask-api --no-pager
            echo "Gunicorn processes:"
            ps aux | grep gunicorn
            echo "Next.js status:"
            pm2 list
